# Position Controllers ---------------------------------------
right_bar_ctrl:
  type: position_controllers/JointPositionController
  joint: right_joint
left_bar_ctrl:
  type: position_controllers/JointPositionController
  joint: left_joint
